export { default as Home } from './Home'
export { default as FeaturedProducts } from './FeaturedProducts'
export { default as Sectors } from './Sectors'
export { default as Customers } from './Customers'
export { default as Statistics } from './Statistics'
