// export images
export { default as ImcetronWhite } from './img/imcetron-wh.png'
export { default as ImcetronBlack } from './img/imcetron-bl.png'
export { default as StatisticsBg } from './img/statistics-bg.png'
export { default as MisionImg } from './img/mision_img.png'
export { default as VisionImg } from './img/vision_img.png'
export { default as EnterpriseImg } from './img/enterprise.png'
export { default as ServicesImg } from './img/services.png'
export { default as HistoryImg } from './img/history.png'
export { default as ServicesFirstImage } from './img/servicesFirstImage.png'
export { default as MaquinaTermoVacio } from './img/maquinaTermoVacio.png'
// export svg
export { default as FacebookW } from './svg/facebook-icon.svg'
export { default as FacebookB } from './svg/facebook-icon-b.svg'
export { default as LinkedinW } from './svg/linkedin-icon.svg'
export { default as LinkedinB } from './svg/linkedin-icon-b.svg'
export { default as ArrowButton } from './svg/arrowButton.svg'
export { default as ChevronLeft } from './svg/chevron-left.svg'
export { default as ChevronRight } from './svg/chevron-right.svg'
